# Generated by Django 5.0.1 on 2024-03-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_clubs_club_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='club_name',
            field=models.CharField(blank=True, default='name', max_length=100),
            preserve_default=False,
        ),
    ]
