# Generated by Django 5.0.1 on 2024-07-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_clubs_club_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubs',
            name='club_name',
        ),
        migrations.AddField(
            model_name='clubs',
            name='club_loft',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='club_manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='club_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
