# Generated by Django 5.0.1 on 2024-07-04 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_clubs_club_name_clubs_club_loft_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubs',
            old_name='club_type',
            new_name='club_name',
        ),
    ]
