# Generated by Django 5.0.1 on 2024-07-04 11:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_club_type_clubs_club_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
