# Generated by Django 5.0.1 on 2024-03-05 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'unique_together': {('latitude', 'longitude')},
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('round_date', models.DateField()),
                ('score', models.IntegerField()),
                ('weather_conditions', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shot_num_per_hole', models.IntegerField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=9)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shot_distance', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.clubs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
