# Generated by Django 5.0.1 on 2024-03-05 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_course_latitude_alter_course_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shot',
            name='shot_num_per_hole',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
