# Generated by Django 5.0.1 on 2024-03-06 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_shot_shot_num_per_hole'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shot',
            name='hole_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shot',
            name='round',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.round'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='round',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
