# Generated by Django 5.0.1 on 2024-03-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_shot_course_shot_hole_num_shot_round_alter_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='round_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
