# Generated by Django 5.0.1 on 2024-03-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_round_score_remove_round_weather_conditions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shot',
            name='shot_num_per_hole',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
