# Generated by Django 5.0.1 on 2024-03-12 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_shot_shot_num_per_hole'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='round',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.round'),
            preserve_default=False,
        ),
    ]
