# Generated by Django 5.0.1 on 2024-03-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_shot_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='hole_par',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
