# Generated by Django 5.0.1 on 2024-03-13 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_shot_hole_par'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shot',
            name='hole_num',
        ),
        migrations.RemoveField(
            model_name='shot',
            name='hole_par',
        ),
        migrations.CreateModel(
            name='Hole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hole_num', models.IntegerField(blank=True, null=True)),
                ('hole_par', models.IntegerField(blank=True, null=True)),
                ('hole_distance', models.IntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.round')),
            ],
        ),
        migrations.AddField(
            model_name='shot',
            name='hole',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.hole'),
            preserve_default=False,
        ),
    ]
