# Generated by Django 5.0.1 on 2024-03-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_shot_hole_num_shot_hole_par'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='end_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='shot',
            name='end_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True),
        ),
    ]
