# Generated by Django 5.0.1 on 2024-03-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_shot_shot_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='round_completed',
            field=models.BooleanField(default=False),
        ),
    ]
