# Generated by Django 4.2.7 on 2024-08-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_round_round_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='last_shot_of_hole',
            field=models.BooleanField(default=False),
        ),
    ]
