# Generated by Django 4.2.7 on 2025-08-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_shot_last_shot_of_hole'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='miss_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
