# Generated by Django 4.2.7 on 2025-08-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_shot_miss_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='test',
            field=models.BooleanField(default=False),
        ),
    ]
