# Generated by Django 4.2.7 on 2025-08-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_miss_type_shot_shot_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='shot_lie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
