# Generated by Django 4.2.7 on 2025-08-20 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_shot_shot_lie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shot',
            name='test',
        ),
    ]
